### ISSUE TITLE
'Could not deserialize key data.'

### ISSUE THREAD

**Issue by quibalu** [SAP-samples/service-ticket-intelligence-jupyter-notebook#1]
Hello, I'm having problems while executing 'sti.list_models()'. I get the following: 'ValueError: Could not deserialize key data'. I've been searching for a solution but have found nothing, hope someone can help me cause I cannot use the service without this issue being solved. I'll attach the final output I get after executing. I've repeatedly checked the credentials copied into the sti_config.ini and those are correct, so the problem has not to do with it. Thanks

`~\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py in _handle_key_loading_error(self)
   1526                 self._lib.ERR_LIB_ASN1,
   1527             )
-> 1528             raise ValueError("Could not deserialize key data.")
   1529 
   1530     def elliptic_curve_supported(self, curve):

ValueError: Could not deserialize key data.`

**Comment by Luca-Hackl** [comment]
I've had the same issue, you need to uninstall pyjwt and then install pyjwt version 1.7.1 via "pip install pyjwt==1.7.1"
